apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-deployment
  labels:
    app: sports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports
  template:
    metadata:
      labels:
        app: sports
    spec:
      containers:
      - name: sports
        image: 261513860477.dkr.ecr.us-east-1.amazonaws.com/shopping-site-sports:3b4e70a83144fe6837049bf1fef10e9b5d1f6c02
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sports-service
  labels:
    app: sports
spec:
  type: ClusterIP
  selector:
    app: sports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
